export const LIST_BANK = [
   "Société Tunisienne de Banque « STB »",
   "Banque Nationale Agricole « BNA »",
   "Banque de l’Habitat « BH »",
   "Banque de Financement des Petites et Moyennes entreprises « BFPME »",
   "Banque Tunisienne de Solidarité « BTS »",
   "Banque de Tunisie et des Emirats « BTE »",
   "Banque Tuniso-Libyenne « BTL »",
   "Tunisian Saudi Bank « TSB »",
   "Banque Zitouna",
   "Al Baraka Bank",
   "Al Wifak International Bank",
   "Amen Bank",
   "Attijari Bank",
   "Arab Tunisian Bank « ATB »",
   "Arab Banking Corporation « ABC »",
   "Banque Internationale Arabe de Tunisie «  BIAT »",
   "Banque de Tunisie « BT »",
   "Banque Tuniso Koweitienne « BTK »",
   "Banque Franco Tunisienne « BFT »",
   "Citi Bank",
   "Qatar National Bank- Tunis « QNB-Tunis »",
   "Union Bancaire de Commerce et d’Industrie «  UBCI »",
   "Union Internationale de Banque «  UIB »"
];